### PR TITLE
Split source code

### PR DESCRIPTION
**Pull request by angstsmurf**
Several people have requested something like this. This is an initial split roughly along "Book" headers, intended as starting point for further splits and reorganization.

It will make Github more useful at the cost of making the built-in Inform 7 IDE less so.

As I can't really make any other pull requests or changes to the code until this is pulled, I'd prefer it if we don't wait too long to decide whether this is something we want or not.

### CODE REVIEW

**Comment by curiousdannii** [comment]
I'm for this, but some of the splits probably aren't needed:

 - Counterfeit Repository A-L, M-R and S-Z could be joined back together
 - The code from Volume 6 could maybe be all be in one extension? That would then make it a very long one, but some of them are so short currently
 - The meta data stuff in Counterfeit Presentation Details should be moved back to story.ni (the first 60 lines)
 - The following multimedia stuff could maybe be split out into its own extension? That would make it easy to exclude them for smaller test builds

Can you remove the "Counterfeit" from the beginning of each, and the change the author of each to either "Counterfeit Monkey" or "CM"? This way it will be easy to see what the body of the code is, and what is just a local version of one of Emily's extensions that we've modified.

**Comment by angstsmurf** [comment]
Right, I'll fix it up!

Of course I was aiming at making all files small enough for Github to show in their entirety, while not quite understanding how Github's limits work.

I'll include that script as well.

What are the downsides to not having Settings.plist in the repository at all? I'd like to avoid both pushing my own local settings changes to the repository by mistake, and overwriting my local settings when updating from remote.

**Comment by curiousdannii** [comment]
> Of course I was aiming at making all files small enough for Github to show in their entirety, while not quite understanding how Github's limits work.

I'm not sure how the limits work either, but I think it depends on the amount of lines changed per file. Any substantial change now won't display a diff because it will all be in the one file. If it's split up somewhat then most changes should work, probably. There may still be some that don't, but we really can't predict what they will be. Artificial divisions (like for the Repository) almost certainly won't make much of a difference.

> What are the downsides to not having Settings.plist in the repository at all? I'd like to avoid both pushing my own local settings changes to the repository by mistake, and overwriting my local settings when updating from remote.

There was a time when the compiler simply wouldn't work without it. If that's not the case any longer then we can just remove it from the repository.

**Comment by angstsmurf** [comment]
The Mac IDE recreates Settings.plist on startup, but I haven't checked anything else.

**Comment by angstsmurf** [comment]
> What if the changelog was also moved? It could also then use markdown formatting

Is there an example of this you could point me to?

**Comment by angstsmurf** [comment]
Done. I added the setup script while keeping the Settings.plist in the .gitignore file. Do you think we should remove it from there?

**Comment by curiousdannii** [comment]
> The Mac IDE recreates Settings.plist on startup, but I haven't checked anything else.

The windows IDE does too. If I was building this on Linux I'd probably use the command line version. So we can remove the file (and keep it in .gitignore). The setup script isn't needed either.

>Is there an example of this you could point me to?

>EDIT: Nevermind. That Google thing sure is great.

The change log looks great! (Super minor nit pick, how would you feel about removing the colons? They're already clearly marked as headings so they're not essential. Could add a line break between the headings and the lists too.)

> Perhaps we should tidy up the extensions as well while we're at it. There are a few that are identical to those in the Public Library. Should these be deleted?

If they're identical then they can be deleted yeah.

(I can't wait for [my secret project](https://github.com/i7/i7el) to be complete.)

**Comment by angstsmurf** [comment]
I'd really like to merge this now. May I?

**Comment by curiousdannii** [comment]
Thank you!

**Pull request merged**
