### PR TITLE
Hardcoded letter hash codes

### PR DESCRIPTION
**Pull request by angstsmurf**
Shave off a couple of seconds at startup by replacing letter hash calculation with a hardcoded list. . Of course this must be updated if we ever add any objects.

Also fixing a couple of obscure bugs in the process.

### CODE REVIEW

**Comment by curiousdannii** [comment]
With glk 0.7.4 we would be able to publish a version with all such startup code recomputed along the lines of http://eblong.com/zarf/glulx/startsavetest.inf

Now glk 0.7.4 isn't supported everywhere yet, and notably Gargoyle doesn't yet. But I can anticipate an extension which would do the same sort of precompution and just store it in an external file, so that players using Gargoyle would have the startup delay only once (unless they deleted that file.)

I think I'd prefer to use that strategy than this. Not needing to worry about keeping it updated is a big plus.

**Comment by angstsmurf** [comment]
That sounds interesting. Tell me more!

I think I'll push those fixes separately. They probably shouldn't have been a part of this PR to begin with.

**Comment by curiousdannii** [comment]
It's pretty straight forward:

1. Check for the existence of a savefile, either in a resource chunk of the blorb, or as an external file
2. Load it if possible (external files for old versions of the game will error)
3. If not, then perform the slow computations
4. Save to the external file
5. If we loaded, we are now here and are ready to go

Then when we're ready to publish, we simply take the file from 4 and insert it into the blorb.

**Comment by curiousdannii** [comment]
@angstsmurf How does that sound to you? Shall we close this pull request, or do you want to merge it in the meantime?

**Comment by angstsmurf** [comment]
Thath sounds good. Let's close this for now.

**Pull request closed without merging**
