### PR TITLE
Reduce undo snapshot size by declaring some initial values in source.

### PR DESCRIPTION
**Pull request by angstsmurf**
See http://www.intfiction.org/forum/viewtopic.php?p=117338#p117338.

"Undo snapshots are compressed (in a very simple way) by comparing to the original data file. So any array which is never changed will not take up (much) snapshot space. If you change the array contents (at game startup or later) then it has to be snapshotted as different."

This PR seems to cut the undo snapshot size by about half, reduces the number of "when play begins" rules, and simplifies the route-finding code.

### CODE REVIEW

**Comment by curiousdannii** [comment]
Do you know how much of a difference it makes after a full game's worth of turns?

**Comment by angstsmurf** [comment]
Unless I've misunderstood something, it seems to be 93 082 bytes with this, 139 830 bytes before.

**Comment by curiousdannii** [comment]
Is that for the undo snapshots? That will be interpreter specific, and I'm not sure how to actually measure them.

**Comment by angstsmurf** [comment]
Yes, for glulxe with profiling enabled.

**Pull request merged**
