### PR TITLE
No waiting for keypresses while testing.

### PR DESCRIPTION
**Pull request by angstsmurf**
This makes full-game testing a lot less painful: it simply skips over any "wait for any key" and "pause the game". Also makes all randomized text the same text every time.

### CODE REVIEW

**Comment by curiousdannii** [comment]
For Kerkerkruip we have a setup where if a file called "noninteractivetests" is present then the game immediately jumps into the tests. That could be a good thing to do here perhaps, so that the randomised stuff would remain randomised while we test it normally.

**Comment by angstsmurf** [comment]
Something like this, perhaps? 

Not that this is all that useful yet. Asking the user to manually name a transcript file is not very non-interactive. And to be able to run several full-game tests in a row I suppose I'll have to implement saving and loading game states automatically.

**Comment by angstsmurf** [comment]
Added two bash scripts and some transcripts and "command scripts" for semi-automated testing. You will have to modify them by adding paths to your own command-line interpreters, and the name of the file of commands you want to pipe into them.

**Comment by angstsmurf** [comment]
Yeah, I suppose this is good enough for now.

**Pull request merged**
