### PR TITLE
Modify Ultra Undo to use tempfiles.

### PR DESCRIPTION
**Pull request by angstsmurf**
This is not pretty, but it seems to work. There is a lot of code here just to keep the value of ultra_undo_counter constant across restores.

EDIT: This now works with the latest code. Surprisingly well in fact, I'm sure I remember this crashing horribly the last time I tested it in May. But perhaps I wasn't thorough enough in my testing this time.

### CODE REVIEW

**Comment by curiousdannii** [comment]
FYI I will be taking a very close look at this, but not in the near future unfortunately. I think we should push this to release 7.

**Comment by curiousdannii** [comment]
If you're still happy with this, let's just merge it.

**Comment by angstsmurf** [comment]
I'm a bit torn on this. It might be nicer than putting lots of save files in the game directory, but we haven't really tested if it causes any problems on mobile devices. I guess a good compromise would be to incorporate this into the existing Ultra Undo as an option, so that you could choose at compile time whether to use temp files or non-temp files for this.

**Comment by angstsmurf** [comment]
I don't think there is much point in keeping this and #22 open, so I'll close them for now.

**Pull request closed without merging**
