### PR TITLE
Add warnings and clarifications to all modified extensions.

### PR DESCRIPTION
**Pull request by angstsmurf**
I have no idea what the proper way to do this is, but I've tried to add comments and warnings to all modified extensions. This is to remind myself which ones I've actually modified and how, and also in the unlikely case that somebody downloads these and tries to use them with their own projects. 

I've added my own name in order to emphasize that these are not official releases by the original authors.

### CODE REVIEW

**Comment by vlaviano** [comment]
See the last couple paragraphs of §27.4. (Authorship) for the official take on this. Also, if any of the extensions have explicit open source licenses, there may be other requirements imposed by those licenses.

**Comment by angstsmurf** [comment]
If I read that correctly, the official take is that I should change the name of the extension from, say, Glulx Entry Points by Emily Short to Glulx Entry Points by Petter Sjölund "based on original code by Emily Short" after changing a single line. That just feels wrong to me. Is that really what people usually do?

**Comment by curiousdannii** [comment]
It would help if you could categorise our local extensions into these two groups:

 - Those which we have modified to update to 6M62 compatibility or to fix bugs, which would be generally useful to all. We should send these modified versions to their original authors and once they get uploaded to the public library we can delete our local versions. We could also put them in the i7/extensions repository.

 - Those which have modifications which are useful only to us. These we will just keep here.

In neither case does section 27.4 really apply to us. I think it is more describing a situation where an Inform 7 extension is being written for the first time (but based on older I6 code), or where the modified extension is intended to exist alongside the original (for translations.) When someone new starts maintaining someone else's extension, the community's convention has been to keep the original author. Emily's extensions keep her name even though they were maintained first by Erik Temple and now by me.

**Comment by angstsmurf** [comment]
The obvious candidates for "useful only to us" are Smarter Parser and Threaded Conversation, as there are improved newer versions already in the public library. The rest might actually be useful to people.

I have a hunch however that some of them, like Notepad and Room Description Control, didn't really need to be changed. We might be able to use the official versions with a bit of work.

I'd prefer to keep the original authors too, but it would be nice to mention somewhere who made the latest changes and whom to bother if you have questions.

Anyway, I'll upload some of these to i7/extensions. It is a start.

**Comment by angstsmurf** [comment]
I don't think there is much point in keeping this and #9 open, so I'll close them for now.

**Pull request closed without merging**
