### PR TITLE
Changes to make it compile on 6M62.

### PR DESCRIPTION
**Pull request by angstsmurf**
Now we're talking.

### CODE REVIEW

**Comment by angstsmurf** [comment]
This is getting unwieldy as a pull request. Or perhaps it always was. @curiousdannii, @vlaviano, @rocketnia, @erkyrath: What do you think is the best way to go forward with this?

**Comment by curiousdannii** [comment]
It was always going to involve a lot of changes. If at the end you felt like you wanted to combine any of the commits together (and your git skills are sufficient, mine wouldn't be!) you could, otherwise we'll just merge it.

**Comment by angstsmurf** [comment]
Fair enough. I'll just carry on then, I suppose. Just let me know if you want me to change anything in particular.

**Comment by vlaviano** [comment]
If I were starting a 6M62 porting effort from scratch, I'd consider breaking the game into smaller modules before porting and porting them individually starting at the leaves of the dependency tree. However, if your current approach is working for you and you're not finding things too unwieldy to work with (as opposed to just the size of the PR being large), then I'd say carry on.

Take a look at [git rebase -i](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) if you want to follow Dannii's suggestion. You'll have to force push to your topic branch after doing so since you've been publishing commits and the commit ids will have changed, but it's not really a big deal unless other people are using your branch.

**Comment by angstsmurf** [comment]
This is actually shaping up rather well. At the moment the most glaring problem is that Test Act2 gets lost somewhere at the roundabout, and I haven’t really investigated why yet. Also we still need a solution for the ”holding too many objects” tests.

I’m sure there is silly stuff in my changes — I am still new to Inform — but I’m thinking it might actually be harder to spot mistakes or dubious stuff if I start to move and squash too many commits. 

The advantage of having a single monolithic file while working with this has been to be able to do global search and replace in the Inform IDE and also to be able to compare it directly to the original version, line by line. 

The code doesn’t really lend itself to compartmentalizing, it is very interdependent and brittle, and moving a single object declaration to another place sometimes breaks things. But it would certainly be nice to have files small enough for Github to show.

**Comment by curiousdannii** [comment]
How is this going? Is it ready to merge yet?

**Comment by angstsmurf** [comment]
That is a good question. What I've been doing lately is mainly to compare new TEST ME transcripts to a transcript of the original 6G60 version, and now I'm down to only one actual problem. But if we don't want to merge anything that will cause known regressions, then I suppose we're not quite there yet until that last one is fixed.

**Comment by curiousdannii** [comment]
It's up to you, you could also just make a bug report for that last regression.

Can I ask you to post up another profile? I'll start working on an extension for better flex performance.

**Comment by angstsmurf** [comment]
When I think about it, It would probably be a good idea to merge this now. It would make it easier to make pull requests for dubious or controversial changes, rather than treating this branch like my personal playground and throwing everything in. And it would of course make it easier for others to contribute.

**Comment by angstsmurf** [comment]
Here is another quick profile run, just playing through the beginning of the game. Let me know if you need anything else.

[(https://gist.github.com/angstsmurf/3fcf545fafbc8c17e6c8c7f2364dd28c)]

**Comment by curiousdannii** [comment]
Is there anything in it now that you don't think should be?

> Here is another quick profile run, just playing through the beginning of the game. Let me know if you need anything else.

That's a debug profile again! Is it possible to set it to give more than the top 10? Even a debug profile would be more insightful if listed more (so that we could get past all the veneer functions).

**Comment by angstsmurf** [comment]
Right, sorry. Here's non-test build, top 30 by total cycles, including child calls:

https://gist.github.com/angstsmurf/60a0a2fbf841a1b141c08dd85c65b323

**Comment by curiousdannii** [comment]
Hooray, thanks and well done for all your work on this!

**Comment by curiousdannii** [comment]
Now none of the Flex functions are showing in those profiles - how strange.

**Pull request merged**
