### PR TITLE
Change "southern" to a boolean attribute and manually set it on rooms…

### PR DESCRIPTION
**Pull request by angstsmurf**
… in that part of the map. As suggested by @erkyrath at http://www.intfiction.org/forum/viewtopic.php?p=108640#p108640

### CODE REVIEW

**Comment by vlaviano** [comment]
Thanks for this. A few comments;

- Do we still need the listing every southern room action? I assume that you used it to make sure that you didn't miss any rooms.
- Perhaps get rid of "Definition: a room is southern:" instead of just commenting it out. We have the git history if we need it again.
- There are a lot of "It/Roomname is X and Y" lines that you've changed to "...is X and Y and southern." Looking at other parts of Emily's code that assign 3 properties to an object, she seems to prefer "It is X, Y and Z." I think that we should make our changes consistent with her style as much as possible. (Lines with only 2 properties saying "It is X and southern." are fine, imo.
- On line 9215, describing Palm Square, the original source code had an extra space. Since you're changing the line, might as well remove it.

**Comment by angstsmurf** [comment]
Thanks for the review. I only received one email. Hopefully I've fixed it all now.

**Comment by vlaviano** [comment]
Just two nits and then I think we're good to go:

Line 8909 - extra period.
Line 9216 - extra space at end of line after period.

**Comment by vlaviano** [comment]
LGTM. Merged. Thanks!

**Comment by curiousdannii** [comment]
The one thing you both missed was to update the changelog!

**Comment by vlaviano** [comment]
In my personal projects, I tend to do that just before putting out a new release, reading through the commit history since the last release and noting significant changes. What's significant enough to make the cut and at what granularity to describe it can depend on what else is included in the release.

If you prefer to do it incrementally, that's cool. I'll remember it when evaluating future pull requests.

How do you want to handle this one?

**Comment by curiousdannii** [comment]
I guess since we're using git now we won't need to keep a detailed changelog, so it could be just a summary. If you're volunteering to look through the commit log when its time for a release then I'm happy to let you handle it! :P

**Comment by vlaviano** [comment]
I guess I asked for that. Ok.

**Pull request merged**
